### ISSUE TITLE
[First Bug] Multiple Widgets are overlapping the whole menu. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [nfm886/skin.cosmic#1] opened 2021-08-06 03:30 UTC
I just noticed this bug when i was trying your skin for the first time. I love your skin and would really like to use it for the future. 

![Bug 1](https://user-images.githubusercontent.com/62456796/128451722-57b081a7-c464-4be6-867d-96414a42b667.PNG)

**_Steps to reproduce_**
1. download seren or tmdb helper
2. Make Widgets like most popular, trending, ect
3. Notice the bug on the menu. 

Hope this helps you out.

**Comment by nfm886** [comment] 2021-08-06 04:26
Hi!
Thanks fo your report. Unfortunately I can't reproduce the issue. I'm using it on 3 devices and everywhere it works just fine: https://streamable.com/lhwg86
Did you come from another skin or it's a fresh install?

**Comment by Goldenfreddy0703** [comment] 2021-08-06 04:43
Came from another skin but also did a fresh install just with my repositorys and userdata. I will try to see how to reproduce this issue again and will try my best to reproduce it again

**Comment by nfm886** [comment] 2021-08-06 04:45
Yeah, sure. Waiting for more info :)

**Comment by nfm886** [comment] 2021-08-06 04:49
> just with my repositorys and userdata.

Did you use AZ2: Resurrection before and have backup with settings in your userdata?

**Comment by Goldenfreddy0703** [comment] 2021-08-06 04:56
Hey, so it turns out its due to the button to enable or disable which makes some widgets unstable so you may have to look into the enable and disable button on the widgets and see if that could possibly be the cause.
![image](https://user-images.githubusercontent.com/62456796/128457834-e5b049b7-088c-44c5-86bb-e5d8feffc6c8.png)

One other thing i encountered is when your select widget in the select widgets tab and you add most popular or most collected or ect, It does not automatically set label.

**Comment by nfm886** [comment] 2021-08-06 05:01
> Hey, so it turns out its due to the button to enable or disable which makes some widgets unstable so you may have to look into the enable and disable button on the widgets and see if that could possibly be the cause.

Ok, got it! It's the root of the issue.



> One other thing i encountered is when your select widget in the select widgets tab and you add most popular or most collected or ect, It does not automatically set label.

I'm aware of this. Tried to fix it but no luck. I have to rewrite some logic behind widgets to make it working.

**Comment by Goldenfreddy0703** [comment] 2021-08-06 05:14
Nice thank you very much for finding the root of this issue, your the best and i can't wait to use this skin for my android tv's.

**Comment by nfm886** [comment] 2021-08-06 06:48
> Hey, so it turns out its due to the button to enable or disable which makes some widgets unstable so you may have to look into the enable and disable button on the widgets and see if that could possibly be the cause.

This, as well as header labels should be now fixed. Would you like to test it?

**Comment by nfm886** [comment] 2021-08-06 13:16
Just pushed an update. Everything should be fixed now. If no, please open new issue. 
Thanks!

**Closed by nfm886** 2021-08-06 13:16 UTC

**Comment by Goldenfreddy0703** [comment] 2021-08-06 16:18
Hey thank you very much. I just woke up so I will be testing it in a few min so thank you.
