### ISSUE TITLE
Favourites doesn't work from widget when trigger spotlight on select is enabled

### ISSUE THREAD

**Issue by meesterexx** [nfm886/skin.cosmic#71] opened 2021-09-28 19:21 UTC
As title, I have a widget for my favourites, when trigger spotlight on select is enabled I am taken to an empty screen (list view) when selecting an item. If I disable spotlight or disable trigger on select, I am taken to the correct content  and view.

**Comment by nfm886** [comment] 2021-09-29 09:52
Thanks for pointing this out. I will try to fix it asap. Unfortunately for now I don't have good solution for this and today + maybe tomorrow I'm kind of busy.

**Comment by meesterexx** [comment] 2021-09-29 12:50
Thanks, not a rush. Just wanted to get it on your radar.

**Comment by nfm886** [comment] 2021-10-01 20:32
Hey, It should be fixed now. I would appreciate your further tests, please download this zip file: https://github.com/nfm886/skin.cosmic/archive/refs/heads/master.zip and give me a feedback, thanks! :)

**Comment by meesterexx** [comment] 2021-10-01 20:53
It works to play the favourite, but then breaks spotlight, In the screenshots below, you can see the favourite widget, and it loads the widget item I select, but when I go back to a different widget (like movies), spotlight still has the information from the favourites widget. I did close kodi and clear cache before taking screenshots, just to be sure.

Favorites widget, selected item launches correctly:
![screenshot00001](https://user-images.githubusercontent.com/13154733/135684635-679fc5ca-e22e-46af-9536-d89f0ef451c8.png)

Moving to the movies widget and selecting first item, still shows favourite item info:
![screenshot00000](https://user-images.githubusercontent.com/13154733/135684820-c3a9425e-87b1-4d0b-adb9-1bf29afe83f1.png)

**Comment by nfm886** [comment] 2021-10-02 08:19
It was hard for me to reproduce it since in most of the time everything was working fine but I made a small change to reduce how often this bug may happen. Please download this zip file: https://github.com/nfm886/skin.cosmic/archive/refs/heads/master.zip and try again :)

**Comment by meesterexx** [comment] 2021-10-02 14:30
That seems to have fixed it. Thanks!

**Comment by nfm886** [comment] 2021-10-02 16:06
Awesome :) I will push a fix later :)

**Closed by nfm886** 2021-10-02 16:06 UTC
